### Auto MPG 데이터셋을 사용하여 1970년대 후반과 1980년대 초반의 자동차 연비를 예측하는 모델을 만듭니다. 이 정보에는 실린더 수, 배기량, 마력(horsepower), 공차 중량 같은 속성이 포함됩니다.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 구글 드라이브 마운트

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Working Directory 설정

In [3]:
import os
os.chdir('/content/drive/MyDrive/data')

파일은 auto-mpg.csv 입니다.

In [4]:
df = pd.read_csv('auto-mpg.csv')

In [5]:
df.head()

    mpg  cyl  displ   hp  weight  accel  yr  origin                       name
0  18.0    8  307.0  130    3504   12.0  70       1  chevrolet chevelle malibu
1  15.0    8  350.0  165    3693   11.5  70       1          buick skylark 320
2  18.0    8  318.0  150    3436   11.0  70       1         plymouth satellite
3  16.0    8  304.0  150    3433   12.0  70       1              amc rebel sst
4  17.0    8  302.0  140    3449   10.5  70       1                ford torino

In [6]:
df.isna().sum()

mpg       0
cyl       0
displ     0
hp        0
weight    0
accel     0
yr        0
origin    0
name      0
dtype: int64

In [7]:
y = df['mpg']

In [8]:
X = df.loc[ : ,'cyl' : 'origin' ]

In [9]:
X.head(2)

   cyl  displ   hp  weight  accel  yr  origin
0    8  307.0  130    3504   12.0  70       1
1    8  350.0  165    3693   11.5  70       1

In [10]:
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [11]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [12]:
sc_X = MinMaxScaler()
sc_y = MinMaxScaler()

In [14]:
X_scaled = sc_X.fit_transform(X)

In [16]:
y.shape

(392,)

In [18]:
y.values.reshape(-1,1)

array([[18. ],
       [15. ],
       [18. ],
       [16. ],
       [17. ],
       [15. ],
       [14. ],
       [14. ],
       [14. ],
       [15. ],
       [15. ],
       [14. ],
       [15. ],
       [14. ],
       [24. ],
       [22. ],
       [18. ],
       [21. ],
       [27. ],
       [26. ],
       [25. ],
       [24. ],
       [25. ],
       [26. ],
       [21. ],
       [10. ],
       [10. ],
       [11. ],
       [ 9. ],
       [27. ],
       [28. ],
       [25. ],
       [19. ],
       [16. ],
       [17. ],
       [19. ],
       [18. ],
       [14. ],
       [14. ],
       [14. ],
       [14. ],
       [12. ],
       [13. ],
       [13. ],
       [18. ],
       [22. ],
       [19. ],
       [18. ],
       [23. ],
       [28. ],
       [30. ],
       [30. ],
       [31. ],
       [35. ],
       [27. ],
       [26. ],
       [24. ],
       [25. ],
       [23. ],
       [20. ],
       [21. ],
       [13. ],
       [14. ],
       [15. ],
       [14. ],
       [17. ],
       [11. ],
       [13. ],
       [12. ],
       [13. ],
       [19. ],
       [15. ],
       [13. ],
       [13. ],
       [14. ],
       [18. ],
       [22. ],
       [21. ],
       [26. ],
       [22. ],
       [28. ],
       [23. ],
       [28. ],
       [27. ],
       [13. ],
       [14. ],
       [13. ],
       [14. ],
       [15. ],
       [12. ],
       [13. ],
       [13. ],
       [14. ],
       [13. ],
       [12. ],
       [13. ],
       [18. ],
       [16. ],
       [18. ],
       [18. ],
       [23. ],
       [26. ],
       [11. ],
       [12. ],
       [13. ],
       [12. ],
       [18. ],
       [20. ],
       [21. ],
       [22. ],
       [18. ],
       [19. ],
       [21. ],
       [26. ],
       [15. ],
       [16. ],
       [29. ],
       [24. ],
       [20. ],
       [19. ],
       [15. ],
       [24. ],
       [20. ],
       [11. ],
       [20. ],
       [19. ],
       [15. ],
       [31. ],
       [26. ],
       [32. ],
       [25. ],
       [16. ],
       [16. ],
       [18. ],
       [16. ],
       [13. ],
       [14. ],
       [14. ],
       [14. ],
       [29. ],
       [26. ],
       [26. ],
       [31. ],
       [32. ],
       [28. ],
       [24. ],
       [26. ],
       [24. ],
       [26. ],
       [31. ],
       [19. ],
       [18. ],
       [15. ],
       [15. ],
       [16. ],
       [15. ],
       [16. ],
       [14. ],
       [17. ],
       [16. ],
       [15. ],
       [18. ],
       [21. ],
       [20. ],
       [13. ],
       [29. ],
       [23. ],
       [20. ],
       [23. ],
       [24. ],
       [25. ],
       [24. ],
       [18. ],
       [29. ],
       [19. ],
       [23. ],
       [23. ],
       [22. ],
       [25. ],
       [33. ],
       [28. ],
       [25. ],
       [25. ],
       [26. ],
       [27. ],
       [17.5],
       [16. ],
       [15.5],
       [14.5],
       [22. ],
       [22. ],
       [24. ],
       [22.5],
       [29. ],
       [24.5],
       [29. ],
       [33. ],
       [20. ],
       [18. ],
       [18.5],
       [17.5],
       [29.5],
       [32. ],
       [28. ],
       [26.5],
       [20. ],
       [13. ],
       [19. ],
       [19. ],
       [16.5],
       [16.5],
       [13. ],
       [13. ],
       [13. ],
       [31.5],
       [30. ],
       [36. ],
       [25.5],
       [33.5],
       [17.5],
       [17. ],
       [15.5],
       [15. ],
       [17.5],
       [20.5],
       [19. ],
       [18.5],
       [16. ],
       [15.5],
       [15.5],
       [16. ],
       [29. ],
       [24.5],
       [26. ],
       [25.5],
       [30.5],
       [33.5],
       [30. ],
       [30.5],
       [22. ],
       [21.5],
       [21.5],
       [43.1],
       [36.1],
       [32.8],
       [39.4],
       [36.1],
       [19.9],
       [19.4],
       [20.2],
       [19.2],
       [20.5],
       [20.2],
       [25.1],
       [20.5],
       [19.4],
       [20.6],
       [20.8],
       [18.6],
       [18.1],
       [19.2],
       [17.7],
       [18.1],
       [17.5],
       [30. ],
       [27.5],
       [27.2],
       [30.9],
       [21.1],
       [23.2],
       [23.8],
       [23.9],
       [20.3],
       [17. ],
       [21.6],
       [16.2],
       [31.5],
       [29.5],
       [21.5],
       [19.8],
       [22.3],
       [20.2],
       [20.6],
       [17. ],
       [17.6],
       [16.5],
       [18.2],
       [16.9],
       [15.5],
       [19.2],
       [18.5],
       [31.9],
       [34.1],
       [35.7],
       [27.4],
       [25.4],
       [23. ],
       [27.2],
       [23.9],
       [34.2],
       [34.5],
       [31.8],
       [37.3],
       [28.4],
       [28.8],
       [26.8],
       [33.5],
       [41.5],
       [38.1],
       [32.1],
       [37.2],
       [28. ],
       [26.4],
       [24.3],
       [19.1],
       [34.3],
       [29.8],
       [31.3],
       [37. ],
       [32.2],
       [46.6],
       [27.9],
       [40.8],
       [44.3],
       [43.4],
       [36.4],
       [30. ],
       [44.6],
       [33.8],
       [29.8],
       [32.7],
       [23.7],
       [35. ],
       [32.4],
       [27.2],
       [26.6],
       [25.8],
       [23.5],
       [30. ],
       [39.1],
       [39. ],
       [35.1],
       [32.3],
       [37. ],
       [37.7],
       [34.1],
       [34.7],
       [34.4],
       [29.9],
       [33. ],
       [33.7],
       [32.4],
       [32.9],
       [31.6],
       [28.1],
       [30.7],
       [25.4],
       [24.2],
       [22.4],
       [26.6],
       [20.2],
       [17.6],
       [28. ],
       [27. ],
       [34. ],
       [31. ],
       [29. ],
       [27. ],
       [24. ],
       [36. ],
       [37. ],
       [31. ],
       [38. ],
       [36. ],
       [36. ],
       [36. ],
       [34. ],
       [38. ],
       [32. ],
       [38. ],
       [25. ],
       [38. ],
       [26. ],
       [22. ],
       [32. ],
       [36. ],
       [27. ],
       [27. ],
       [44. ],
       [32. ],
       [28. ],
       [31. ]])

In [20]:
y_scaled = sc_y.fit_transform(y.values.reshape(-1,1))

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

In [ ]:
# 딥러닝 모델링

In [23]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
def build_model( input_dim ) :
  model = Sequential()
  model.add( keras.Input(shape=(input_dim,)) )
  model.add( Dense(64, activation='relu') )
  model.add( Dense(64, activation='relu') )
  model.add( Dense(1, activation='linear'))
  model.compile( optimizer='adam', loss='mse', metrics=['mae'] )
  return model

In [27]:
model = build_model( X_train.shape[1] )

In [28]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,737 (18.50 KB)

 Trainable params: 4,737 (18.50 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
X_train.shape

(313, 7)

In [30]:
history = model.fit(X_train, y_train, epochs=500, validation_split= 0.2 )

Epoch 1/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.1163 - mae: 0.2724 - val_loss: 0.0456 - val_mae: 0.1850
Epoch 2/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0320 - mae: 0.1515 - val_loss: 0.0153 - val_mae: 0.0965
Epoch 3/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0141 - mae: 0.0969 - val_loss: 0.0140 - val_mae: 0.0942
Epoch 4/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0162 - mae: 0.1008 - val_loss: 0.0108 - val_mae: 0.0812
Epoch 5/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0132 - mae: 0.0892 - val_loss: 0.0108 - val_mae: 0.0832
Epoch 6/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0108 - mae: 0.0818 - val_loss: 0.0113 - val_mae: 0.0848
Epoch 7/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0096 - mae: 0.0764 - val_loss: 0.0105 - val_mae: 0.0819
Epoch 8/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0084 - mae: 0.0700 - val_loss: 0.0092 - val_mae: 0.0773
Epoch 9/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0086 - mae: 0.0715 - val_loss: 0.0092 - val_mae: 0.0765
Epoch 10/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0095 - mae: 0.0734 - val_loss: 0.0095 - val_mae: 0.0782
Epoch 11/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0088 - mae: 0.0693 - val_loss: 0.0090 - val_mae: 0.0755
Epoch 12/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0065 - mae: 0.0606 - val_loss: 0.0082 - val_mae: 0.0716
Epoch 13/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0078 - mae: 0.0655 - val_loss: 0.0085 - val_mae: 0.0724
Epoch 14/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0072 - mae: 0.0621 - val_loss: 0.0078 - val_mae: 0.0693
Epoch 15/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0061 - mae: 0.0576 - val_loss: 0.0082 - val_mae: 0.0706
Epoch 16/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0062 - mae: 0.0587 - val_loss: 0.0072 - val_mae: 0.0658
Epoch 17/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0069 - mae: 0.0600 - val_loss: 0.0078 - val_mae: 0.0681
Epoch 18/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0595 - val_loss: 0.0069 - val_mae: 0.0649
Epoch 19/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0559 - val_loss: 0.0072 - val_mae: 0.0647
Epoch 20/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0052 - mae: 0.0535 - val_loss: 0.0068 - val_mae: 0.0629
Epoch 21/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0580 - val_loss: 0.0072 - val_mae: 0.0649
Epoch 22/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0567 - val_loss: 0.0068 - val_mae: 0.0626
Epoch 23/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0052 - mae: 0.0541 - val_loss: 0.0062 - val_mae: 0.0605
Epoch 24/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0058 - mae: 0.0574 - val_loss: 0.0068 - val_mae: 0.0618
Epoch 25/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0544 - val_loss: 0.0062 - val_mae: 0.0600
Epoch 26/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0053 - mae: 0.0541 - val_loss: 0.0065 - val_mae: 0.0607
Epoch 27/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0051 - mae: 0.0521 - val_loss: 0.0063 - val_mae: 0.0592
Epoch 28/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0049 - mae: 0.0517 - val_loss: 0.0058 - val_mae: 0.0577
Epoch 29/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0543 - val_loss: 0.0067 - val_mae: 0.0610
Epoch 30/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0060 - mae: 0.0564 - val_loss: 0.0059 - val_mae: 0.0582
Epoch 31/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0048 - mae: 0.0496 - val_loss: 0.0058 - val_mae: 0.0573
Epoch 32/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0048 - mae: 0.0500 - val_loss: 0.0062 - val_mae: 0.0582
Epoch 33/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0047 - mae: 0.0512 - val_loss: 0.0056 - val_mae: 0.0580
Epoch 34/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0044 - mae: 0.0495 - val_loss: 0.0066 - val_mae: 0.0594
Epoch 35/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0058 - mae: 0.0552 - val_loss: 0.0055 - val_mae: 0.0556
Epoch 36/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0044 - mae: 0.0477 - val_loss: 0.0058 - val_mae: 0.0565
Epoch 37/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0052 - mae: 0.0506 - val_loss: 0.0057 - val_mae: 0.0554
Epoch 38/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0051 - mae: 0.0523 - val_loss: 0.0056 - val_mae: 0.0563
Epoch 39/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0047 - mae: 0.0499 - val_loss: 0.0054 - val_mae: 0.0543
Epoch 40/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0045 - mae: 0.0479 - val_loss: 0.0056 - val_mae: 0.0549
Epoch 41/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044 - mae: 0.0477 - val_loss: 0.0054 - val_mae: 0.0546
Epoch 42/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0049 - mae: 0.0499 - val_loss: 0.0063 - val_mae: 0.0579
Epoch 43/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041 - mae: 0.0464 - val_loss: 0.0050 - val_mae: 0.0536
Epoch 44/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0046 - mae: 0.0512 - val_loss: 0.0053 - val_mae: 0.0545
Epoch 45/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0047 - mae: 0.0487 - val_loss: 0.0060 - val_mae: 0.0568
Epoch 46/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041 - mae: 0.0458 - val_loss: 0.0050 - val_mae: 0.0533
Epoch 47/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0049 - mae: 0.0492 - val_loss: 0.0056 - val_mae: 0.0545
Epoch 48/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0038 - mae: 0.0443 - val_loss: 0.0051 - val_mae: 0.0533
Epoch 49/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mae: 0.0481 - val_loss: 0.0053 - val_mae: 0.0533
Epoch 50/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0035 - mae: 0.0430 - val_loss: 0.0056 - val_mae: 0.0542
Epoch 51/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0047 - mae: 0.0485 - val_loss: 0.0050 - val_mae: 0.0547
Epoch 52/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0053 - mae: 0.0527 - val_loss: 0.0056 - val_mae: 0.0543
Epoch 53/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0040 - mae: 0.0464 - val_loss: 0.0050 - val_mae: 0.0537
Epoch 54/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0045 - mae: 0.0486 - val_loss: 0.0051 - val_mae: 0.0528
Epoch 55/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0041 - mae: 0.0468 - val_loss: 0.0049 - val_mae: 0.0514
Epoch 56/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0036 - mae: 0.0442 - val_loss: 0.0049 - val_mae: 0.0520
Epoch 57/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0038 - mae: 0.0456 - val_loss: 0.0054 - val_mae: 0.0528
Epoch 58/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0049 - mae: 0.0507 - val_loss: 0.0050 - val_mae: 0.0523
Epoch 59/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044 - mae: 0.0488 - val_loss: 0.0049 - val_mae: 0.0537
Epoch 60/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0045 - mae: 0.0494 - val_loss: 0.0056 - val_mae: 0.0534
Epoch 61/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mae: 0.0489 - val_loss: 0.0055 - val_mae: 0.0536
Epoch 62/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0042 - mae: 0.0468 - val_loss: 0.0047 - val_mae: 0.0512
Epoch 63/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0036 - mae: 0.0432 - val_loss: 0.0051 - val_mae: 0.0526
Epoch 64/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0042 - mae: 0.0465 - val_loss: 0.0055 - val_mae: 0.0526
Epoch 65/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0045 - mae: 0.0491 - val_loss: 0.0049 - val_mae: 0.0507
Epoch 66/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041 - mae: 0.0475 - val_loss: 0.0054 - val_mae: 0.0526
Epoch 67/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0454 - val_loss: 0.0051 - val_mae: 0.0510
Epoch 68/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0443 - val_loss: 0.0046 - val_mae: 0.0507
Epoch 69/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0445 - val_loss: 0.0051 - val_mae: 0.0512
Epoch 70/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0037 - mae: 0.0450 - val_loss: 0.0049 - val_mae: 0.0507
Epoch 71/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0050 - val_mae: 0.0519
Epoch 72/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0047 - mae: 0.0510 - val_loss: 0.0064 - val_mae: 0.0577
Epoch 73/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0045 - mae: 0.0508 - val_loss: 0.0046 - val_mae: 0.0524
Epoch 74/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mae: 0.0491 - val_loss: 0.0047 - val_mae: 0.0496
Epoch 75/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0049 - mae: 0.0486 - val_loss: 0.0064 - val_mae: 0.0571
Epoch 76/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0051 - mae: 0.0496 - val_loss: 0.0047 - val_mae: 0.0509
Epoch 77/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0040 - mae: 0.0436 - val_loss: 0.0046 - val_mae: 0.0504
Epoch 78/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0040 - mae: 0.0457 - val_loss: 0.0054 - val_mae: 0.0525
Epoch 79/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0045 - mae: 0.0466 - val_loss: 0.0051 - val_mae: 0.0512
Epoch 80/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0042 - mae: 0.0470 - val_loss: 0.0050 - val_mae: 0.0509
Epoch 81/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0418 - val_loss: 0.0048 - val_mae: 0.0514
Epoch 82/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0034 - mae: 0.0421 - val_loss: 0.0046 - val_mae: 0.0494
Epoch 83/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0036 - mae: 0.0438 - val_loss: 0.0043 - val_mae: 0.0501
Epoch 84/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0038 - mae: 0.0461 - val_loss: 0.0048 - val_mae: 0.0503
Epoch 85/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0039 - mae: 0.0453 - val_loss: 0.0047 - val_mae: 0.0498
Epoch 86/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0044 - mae: 0.0463 - val_loss: 0.0050 - val_mae: 0.0512
Epoch 87/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0037 - mae: 0.0431 - val_loss: 0.0045 - val_mae: 0.0495
Epoch 88/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0036 - mae: 0.0426 - val_loss: 0.0047 - val_mae: 0.0490
Epoch 89/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0443 - val_loss: 0.0049 - val_mae: 0.0517
Epoch 90/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0424 - val_loss: 0.0044 - val_mae: 0.0494
Epoch 91/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037 - mae: 0.0440 - val_loss: 0.0049 - val_mae: 0.0507
Epoch 92/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0046 - mae: 0.0462 - val_loss: 0.0047 - val_mae: 0.0497
Epoch 93/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0040 - mae: 0.0437 - val_loss: 0.0051 - val_mae: 0.0507
Epoch 94/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0030 - mae: 0.0403 - val_loss: 0.0045 - val_mae: 0.0488
Epoch 95/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0037 - mae: 0.0446 - val_loss: 0.0046 - val_mae: 0.0498
Epoch 96/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0040 - mae: 0.0459 - val_loss: 0.0047 - val_mae: 0.0496
Epoch 97/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0039 - mae: 0.0433 - val_loss: 0.0052 - val_mae: 0.0514
Epoch 98/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0032 - mae: 0.0422 - val_loss: 0.0048 - val_mae: 0.0502
Epoch 99/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0034 - mae: 0.0411 - val_loss: 0.0042 - val_mae: 0.0492
Epoch 100/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0036 - mae: 0.0449 - val_loss: 0.0044 - val_mae: 0.0496
Epoch 101/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0039 - mae: 0.0453 - val_loss: 0.0063 - val_mae: 0.0569
Epoch 102/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0038 - mae: 0.0463 - val_loss: 0.0047 - val_mae: 0.0501
Epoch 103/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0035 - mae: 0.0416 - val_loss: 0.0045 - val_mae: 0.0496
Epoch 104/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0035 - mae: 0.0422 - val_loss: 0.0050 - val_mae: 0.0510
Epoch 105/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0034 - mae: 0.0420 - val_loss: 0.0045 - val_mae: 0.0491
Epoch 106/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0039 - mae: 0.0444 - val_loss: 0.0045 - val_mae: 0.0484
Epoch 107/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0039 - mae: 0.0451 - val_loss: 0.0071 - val_mae: 0.0613
Epoch 108/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0045 - mae: 0.0490 - val_loss: 0.0046 - val_mae: 0.0497
Epoch 109/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0032 - mae: 0.0401 - val_loss: 0.0042 - val_mae: 0.0482
Epoch 110/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0451 - val_loss: 0.0054 - val_mae: 0.0523
Epoch 111/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0034 - mae: 0.0413 - val_loss: 0.0045 - val_mae: 0.0502
Epoch 112/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027 - mae: 0.0381 - val_loss: 0.0045 - val_mae: 0.0480
Epoch 113/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0434 - val_loss: 0.0048 - val_mae: 0.0512
Epoch 114/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0030 - mae: 0.0411 - val_loss: 0.0041 - val_mae: 0.0477
Epoch 115/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0033 - mae: 0.0425 - val_loss: 0.0042 - val_mae: 0.0483
Epoch 116/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0043 - mae: 0.0465 - val_loss: 0.0047 - val_mae: 0.0497
Epoch 117/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0031 - mae: 0.0398 - val_loss: 0.0053 - val_mae: 0.0511
Epoch 118/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0036 - mae: 0.0443 - val_loss: 0.0048 - val_mae: 0.0494
Epoch 119/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0036 - mae: 0.0435 - val_loss: 0.0041 - val_mae: 0.0503
Epoch 120/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0040 - mae: 0.0470 - val_loss: 0.0047 - val_mae: 0.0489
Epoch 121/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0036 - mae: 0.0434 - val_loss: 0.0059 - val_mae: 0.0544
Epoch 122/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0028 - mae: 0.0403 - val_loss: 0.0043 - val_mae: 0.0483
Epoch 123/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0033 - mae: 0.0403 - val_loss: 0.0044 - val_mae: 0.0490
Epoch 124/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0045 - mae: 0.0480 - val_loss: 0.0056 - val_mae: 0.0531
Epoch 125/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0035 - mae: 0.0432 - val_loss: 0.0053 - val_mae: 0.0516
Epoch 126/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0036 - mae: 0.0445 - val_loss: 0.0044 - val_mae: 0.0518
Epoch 127/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0032 - mae: 0.0420 - val_loss: 0.0048 - val_mae: 0.0494
Epoch 128/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0039 - mae: 0.0423 - val_loss: 0.0050 - val_mae: 0.0511
Epoch 129/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0036 - mae: 0.0422 - val_loss: 0.0044 - val_mae: 0.0479
Epoch 130/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0416 - val_loss: 0.0044 - val_mae: 0.0500
Epoch 131/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0035 - mae: 0.0414 - val_loss: 0.0048 - val_mae: 0.0494
Epoch 132/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030 - mae: 0.0396 - val_loss: 0.0043 - val_mae: 0.0478
Epoch 133/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0036 - mae: 0.0438 - val_loss: 0.0046 - val_mae: 0.0489
Epoch 134/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0032 - mae: 0.0401 - val_loss: 0.0058 - val_mae: 0.0533
Epoch 135/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0035 - mae: 0.0426 - val_loss: 0.0045 - val_mae: 0.0495
Epoch 136/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030 - mae: 0.0400 - val_loss: 0.0041 - val_mae: 0.0484
Epoch 137/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0413 - val_loss: 0.0044 - val_mae: 0.0485
Epoch 138/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0396 - val_loss: 0.0050 - val_mae: 0.0497
Epoch 139/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033 - mae: 0.0416 - val_loss: 0.0043 - val_mae: 0.0501
Epoch 140/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0035 - mae: 0.0421 - val_loss: 0.0054 - val_mae: 0.0526
Epoch 141/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0032 - mae: 0.0416 - val_loss: 0.0043 - val_mae: 0.0488
Epoch 142/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030 - mae: 0.0402 - val_loss: 0.0044 - val_mae: 0.0488
Epoch 143/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0030 - mae: 0.0393 - val_loss: 0.0045 - val_mae: 0.0484
Epoch 144/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0029 - mae: 0.0395 - val_loss: 0.0044 - val_mae: 0.0488
Epoch 145/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0035 - mae: 0.0411 - val_loss: 0.0053 - val_mae: 0.0516
Epoch 146/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0031 - mae: 0.0414 - val_loss: 0.0056 - val_mae: 0.0530
Epoch 147/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mae: 0.0501 - val_loss: 0.0046 - val_mae: 0.0502
Epoch 148/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0032 - mae: 0.0405 - val_loss: 0.0053 - val_mae: 0.0513
Epoch 149/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0037 - mae: 0.0428 - val_loss: 0.0050 - val_mae: 0.0501
Epoch 150/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033 - mae: 0.0404 - val_loss: 0.0042 - val_mae: 0.0494
Epoch 151/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0039 - mae: 0.0446 - val_loss: 0.0044 - val_mae: 0.0514
Epoch 152/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0047 - mae: 0.0488 - val_loss: 0.0046 - val_mae: 0.0489
Epoch 153/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037 - mae: 0.0430 - val_loss: 0.0057 - val_mae: 0.0539
Epoch 154/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0038 - mae: 0.0440 - val_loss: 0.0054 - val_mae: 0.0520
Epoch 155/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0038 - mae: 0.0467 - val_loss: 0.0043 - val_mae: 0.0531
Epoch 156/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0447 - val_loss: 0.0041 - val_mae: 0.0497
Epoch 157/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0036 - mae: 0.0451 - val_loss: 0.0054 - val_mae: 0.0516
Epoch 158/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0029 - mae: 0.0404 - val_loss: 0.0043 - val_mae: 0.0483
Epoch 159/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0035 - mae: 0.0418 - val_loss: 0.0043 - val_mae: 0.0515
Epoch 160/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0435 - val_loss: 0.0041 - val_mae: 0.0489
Epoch 161/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0415 - val_loss: 0.0050 - val_mae: 0.0498
Epoch 162/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027 - mae: 0.0380 - val_loss: 0.0044 - val_mae: 0.0495
Epoch 163/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0413 - val_loss: 0.0042 - val_mae: 0.0507
Epoch 164/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0396 - val_loss: 0.0043 - val_mae: 0.0487
Epoch 165/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0397 - val_loss: 0.0048 - val_mae: 0.0503
Epoch 166/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0407 - val_loss: 0.0046 - val_mae: 0.0497
Epoch 167/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0039 - mae: 0.0447 - val_loss: 0.0045 - val_mae: 0.0496
Epoch 168/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0032 - mae: 0.0382 - val_loss: 0.0051 - val_mae: 0.0512
Epoch 169/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0032 - mae: 0.0402 - val_loss: 0.0046 - val_mae: 0.0495
Epoch 170/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0399 - val_loss: 0.0049 - val_mae: 0.0502
Epoch 171/500

이 그래프를 보면 수 백번 에포크를 진행한 이후에는 모델이 거의 향상되지 않는 것 같습니다. model.fit 메서드를 수정하여 검증 점수가 향상되지 않으면 자동으로 훈련을 멈추도록 만들어 보죠. 에포크마다 훈련 상태를 점검하기 위해 EarlyStopping 콜백(callback)을 사용하겠습니다. 지정된 에포크 횟수 동안 성능 향상이 없으면 자동으로 훈련이 멈춥니다.

이 콜백에 대해 더 자세한 내용은 여기를 참고하세요.[링크 텍스트](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping)